[package]
name = "software_testing_project"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6"

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
name = "example_min"
harness = false

[[bench]]
name = "total_time"
harness = false

[[bench]]
name = "positions_per_second"
harness = false
